require "caleb.options"
require "caleb.keymaps"
require "caleb.plugins"
require "caleb.colorscheme"
require "caleb.cmp"
require "caleb.lsp"
require "caleb.treesitter"
require "caleb.telescope"
require "caleb.autopairs"
require "caleb.comment"
require "caleb.gitsigns"
-- require "caleb.nvim-tree"
require "caleb.bufferline"
require "caleb.toggleterm"
require "caleb.lualine"
